using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SysBase.Core.Models;

namespace SysBase.Repository.Seeds
{
    internal class MenuSeed : IEntityTypeConfiguration<Menu>
    {
        public void Configure(EntityTypeBuilder<Menu> builder)
        {
            builder.HasData(
                new Menu { Id = 1, ControllerName = "Menu", TableName = "Menus", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Menüler", Page = "#", Visibility = false, SpecialVisibility = false, Sequence = 10, Icon = "fas fa-bars", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 2, ControllerName = "Menu", TableName = "Menus", TablePrimaryColumn = "Id", UpMenuId = 1, Name = "Menü Kurulum", Page = "/Admin/Menu/Add", Visibility = true, SpecialVisibility = false, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 3, ControllerName = "Menu", TableName = "Menus", TablePrimaryColumn = "Id", UpMenuId = 1, Name = "Menü Güncelle", Page = "/Admin/Menu/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 4, ControllerName = "User", TableName = "Users", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Kullanıcılar", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1000, Icon = "fas fa-users-cog", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 5, ControllerName = "User", TableName = "Users", TablePrimaryColumn = "Id", UpMenuId = 4, Name = "Kullanıcı Ekle", Page = "/Admin/User/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 6, ControllerName = "User", TableName = "Users", TablePrimaryColumn = "Id", UpMenuId = 4, Name = "Kullanıcı Listele", Page = "/Admin/User/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 7, ControllerName = "Config", TableName = "Configs", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Ayarlar", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1020, Icon = "fas fa-cog", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 8, ControllerName = "Config", TableName = "Configs", TablePrimaryColumn = "Id", UpMenuId = 7, Name = "Ayar Güncelle", Page = "/Admin/Config/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 9, ControllerName = "Language", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Site Dilleri", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1030, Icon = "fas fa-language", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 10, ControllerName = "Language", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 9, Name = "Dil Ekle", Page = "/Admin/Language/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 11, ControllerName = "Language", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 9, Name = "Dil Ve Değerler", Page = "/Admin/Language/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 12, ControllerName = "Language", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 9, Name = "Dil Keyler", Page = "/Admin/Language/KeyList", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 13, ControllerName = "PanelLanguage", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Panel Dilleri", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1040, Icon = "fas fa-language", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 14, ControllerName = "PanelLanguage", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 13, Name = "Dil Ekle", Page = "/Admin/PanelLanguage/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 15, ControllerName = "PanelLanguage", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 13, Name = "Dil Ve Değerler", Page = "/Admin/PanelLanguage/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 16, ControllerName = "PanelLanguage", TableName = "Languages", TablePrimaryColumn = "Id", UpMenuId = 13, Name = "Dil Keyler", Page = "/Admin/PanelLanguage/KeyList", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 17, ControllerName = "Notification", TableName = "Notifications", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Bildirimler", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1050, Icon = "fas fa-bell", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 18, ControllerName = "Notification", TableName = "Notifications", TablePrimaryColumn = "Id", UpMenuId = 17, Name = "Bildirim Ekle", Page = "/Admin/Notification/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 19, ControllerName = "Notification", TableName = "Notifications", TablePrimaryColumn = "Id", UpMenuId = 17, Name = "Bildirim Listele", Page = "/Admin/Notification/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 20, ControllerName = "Page", TableName = "Pages", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Sayfalar", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1060, Icon = "fas fa-file-alt", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 21, ControllerName = "Page", TableName = "Pages", TablePrimaryColumn = "Id", UpMenuId = 20, Name = "Sayfa Ekle", Page = "/Admin/Page/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 22, ControllerName = "Page", TableName = "Pages", TablePrimaryColumn = "Id", UpMenuId = 20, Name = "Sayfa Listele", Page = "/Admin/Page/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 23, ControllerName = "User", TableName = "Users", TablePrimaryColumn = "Id", UpMenuId = 4, Name = "Profil Güncelle", Page = "/Admin/User/ProfileList", Visibility = false, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 24, ControllerName = "User", TableName = "Users", TablePrimaryColumn = "Id", UpMenuId = 4, Name = "Şifre Değiştir", Page = "/Admin/User/ChangePasswordList", Visibility = false, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 25, ControllerName = "Role", TableName = "Roles", TablePrimaryColumn = "Id", UpMenuId = 0, Name = "Roleler", Page = "#", Visibility = true, SpecialVisibility = true, Sequence = 1000, Icon = "fas fa-database", Type = 0, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 26, ControllerName = "Role", TableName = "Roles", TablePrimaryColumn = "Id", UpMenuId = 25, Name = "Role Ekle", Page = "/Admin/Role/Add", Visibility = true, SpecialVisibility = true, Sequence = 1, Icon = "", Type = 1, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now },
                new Menu { Id = 27, ControllerName = "Role", TableName = "Roles", TablePrimaryColumn = "Id", UpMenuId = 25, Name = "Role Listele", Page = "/Admin/Role/List", Visibility = true, SpecialVisibility = true, Sequence = 2, Icon = "", Type = 2, VideoUrl = "", BaseMenuId = 0, CreatedDate = DateTime.Now }
            );
        }
    }
}
