//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="basvururequest", Namespace="http://schemas.datacontract.org/2004/07/PartnerService")]
    public partial class basvururequest : object
    {
        
        private string AciklamaField;
        
        private string AdSoyadField;
        
        private bool AvukatField;
        
        private string CepTelefonuField;
        
        private string DeliveryTypeField;
        
        private string DogumTarihiField;
        
        private string DogumYeriField;
        
        private int DurumField;
        
        private string EmailAdresiSertifikadaGorulsunField;
        
        private string EpostaField;
        
        private string FaturaAdresiCepTelefonuField;
        
        private string FaturaAdresiDetayField;
        
        private string FaturaAdresiFaxField;
        
        private string FaturaAdresiIlField;
        
        private string FaturaAdresiIlceField;
        
        private string FaturaAdresiPostaKoduField;
        
        private string FaturaAdresiTelefonField;
        
        private string FaxField;
        
        private string FirmaUnvaniField;
        
        private string GizliSoruField;
        
        private string IPAdresiField;
        
        private string IlField;
        
        private string IlceField;
        
        private string KayitIDField;
        
        private string KurulumAdresiCepTelefonuField;
        
        private string KurulumAdresiDetayField;
        
        private string KurulumAdresiFaxField;
        
        private string KurulumAdresiIlField;
        
        private string KurulumAdresiIlceField;
        
        private string KurulumAdresiPostaKoduField;
        
        private string KurulumAdresiTelefonField;
        
        private string OdemeMiktariField;
        
        private string OdemeSekliField;
        
        private string PdfErisimTokenField;
        
        private string PostaKoduField;
        
        private string ProjeAdiField;
        
        private string SiparisAdiField;
        
        private string SirketField;
        
        private string SonKullanmaTarihiField;
        
        private string TCKimlikNoField;
        
        private string TCSeriNoField;
        
        private string TelefonField;
        
        private string Teslimat_AdresiField;
        
        private string UyrukField;
        
        private string VergiDairesiField;
        
        private string VergiNoField;
        
        private string YilField;
        
        private string emuhurkisiField;
        
        private string emuhurtcField;
        
        private string emuhurvergidairesiField;
        
        private string emuhurvergiilField;
        
        private string emuhurverginoField;
        
        private string guvenliksozcuguField;
        
        private string ikincikisiadsoyadField;
        
        private string ikincikisitcField;
        
        private string ilkKullanmaTarihiField;
        
        private bool isedevletField;
        
        private bool istestField;
        
        private bool izinField;
        
        private string kanalField;
        
        private string kepadresField;
        
        private bool kimlikdogrulandiField;
        
        private bool kurulumVarMiField;
        
        private string kvkonaytikField;
        
        private string nvidogrulamaField;
        
        private string onaytikField;
        
        private string pasaportnoField;
        
        private string passField;
        
        private CrmService.urun[] urunlerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdSoyad
        {
            get
            {
                return this.AdSoyadField;
            }
            set
            {
                this.AdSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Avukat
        {
            get
            {
                return this.AvukatField;
            }
            set
            {
                this.AvukatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CepTelefonu
        {
            get
            {
                return this.CepTelefonuField;
            }
            set
            {
                this.CepTelefonuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryType
        {
            get
            {
                return this.DeliveryTypeField;
            }
            set
            {
                this.DeliveryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumTarihi
        {
            get
            {
                return this.DogumTarihiField;
            }
            set
            {
                this.DogumTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYeri
        {
            get
            {
                return this.DogumYeriField;
            }
            set
            {
                this.DogumYeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAdresiSertifikadaGorulsun
        {
            get
            {
                return this.EmailAdresiSertifikadaGorulsunField;
            }
            set
            {
                this.EmailAdresiSertifikadaGorulsunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eposta
        {
            get
            {
                return this.EpostaField;
            }
            set
            {
                this.EpostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiCepTelefonu
        {
            get
            {
                return this.FaturaAdresiCepTelefonuField;
            }
            set
            {
                this.FaturaAdresiCepTelefonuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiDetay
        {
            get
            {
                return this.FaturaAdresiDetayField;
            }
            set
            {
                this.FaturaAdresiDetayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiFax
        {
            get
            {
                return this.FaturaAdresiFaxField;
            }
            set
            {
                this.FaturaAdresiFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiIl
        {
            get
            {
                return this.FaturaAdresiIlField;
            }
            set
            {
                this.FaturaAdresiIlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiIlce
        {
            get
            {
                return this.FaturaAdresiIlceField;
            }
            set
            {
                this.FaturaAdresiIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiPostaKodu
        {
            get
            {
                return this.FaturaAdresiPostaKoduField;
            }
            set
            {
                this.FaturaAdresiPostaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaturaAdresiTelefon
        {
            get
            {
                return this.FaturaAdresiTelefonField;
            }
            set
            {
                this.FaturaAdresiTelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmaUnvani
        {
            get
            {
                return this.FirmaUnvaniField;
            }
            set
            {
                this.FirmaUnvaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GizliSoru
        {
            get
            {
                return this.GizliSoruField;
            }
            set
            {
                this.GizliSoruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAdresi
        {
            get
            {
                return this.IPAdresiField;
            }
            set
            {
                this.IPAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KayitID
        {
            get
            {
                return this.KayitIDField;
            }
            set
            {
                this.KayitIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiCepTelefonu
        {
            get
            {
                return this.KurulumAdresiCepTelefonuField;
            }
            set
            {
                this.KurulumAdresiCepTelefonuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiDetay
        {
            get
            {
                return this.KurulumAdresiDetayField;
            }
            set
            {
                this.KurulumAdresiDetayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiFax
        {
            get
            {
                return this.KurulumAdresiFaxField;
            }
            set
            {
                this.KurulumAdresiFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiIl
        {
            get
            {
                return this.KurulumAdresiIlField;
            }
            set
            {
                this.KurulumAdresiIlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiIlce
        {
            get
            {
                return this.KurulumAdresiIlceField;
            }
            set
            {
                this.KurulumAdresiIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiPostaKodu
        {
            get
            {
                return this.KurulumAdresiPostaKoduField;
            }
            set
            {
                this.KurulumAdresiPostaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KurulumAdresiTelefon
        {
            get
            {
                return this.KurulumAdresiTelefonField;
            }
            set
            {
                this.KurulumAdresiTelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OdemeMiktari
        {
            get
            {
                return this.OdemeMiktariField;
            }
            set
            {
                this.OdemeMiktariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OdemeSekli
        {
            get
            {
                return this.OdemeSekliField;
            }
            set
            {
                this.OdemeSekliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfErisimToken
        {
            get
            {
                return this.PdfErisimTokenField;
            }
            set
            {
                this.PdfErisimTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostaKodu
        {
            get
            {
                return this.PostaKoduField;
            }
            set
            {
                this.PostaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjeAdi
        {
            get
            {
                return this.ProjeAdiField;
            }
            set
            {
                this.ProjeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiparisAdi
        {
            get
            {
                return this.SiparisAdiField;
            }
            set
            {
                this.SiparisAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sirket
        {
            get
            {
                return this.SirketField;
            }
            set
            {
                this.SirketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonKullanmaTarihi
        {
            get
            {
                return this.SonKullanmaTarihiField;
            }
            set
            {
                this.SonKullanmaTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCSeriNo
        {
            get
            {
                return this.TCSeriNoField;
            }
            set
            {
                this.TCSeriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Teslimat_Adresi
        {
            get
            {
                return this.Teslimat_AdresiField;
            }
            set
            {
                this.Teslimat_AdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VergiDairesi
        {
            get
            {
                return this.VergiDairesiField;
            }
            set
            {
                this.VergiDairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VergiNo
        {
            get
            {
                return this.VergiNoField;
            }
            set
            {
                this.VergiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yil
        {
            get
            {
                return this.YilField;
            }
            set
            {
                this.YilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emuhurkisi
        {
            get
            {
                return this.emuhurkisiField;
            }
            set
            {
                this.emuhurkisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emuhurtc
        {
            get
            {
                return this.emuhurtcField;
            }
            set
            {
                this.emuhurtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emuhurvergidairesi
        {
            get
            {
                return this.emuhurvergidairesiField;
            }
            set
            {
                this.emuhurvergidairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emuhurvergiil
        {
            get
            {
                return this.emuhurvergiilField;
            }
            set
            {
                this.emuhurvergiilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emuhurvergino
        {
            get
            {
                return this.emuhurverginoField;
            }
            set
            {
                this.emuhurverginoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guvenliksozcugu
        {
            get
            {
                return this.guvenliksozcuguField;
            }
            set
            {
                this.guvenliksozcuguField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ikincikisiadsoyad
        {
            get
            {
                return this.ikincikisiadsoyadField;
            }
            set
            {
                this.ikincikisiadsoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ikincikisitc
        {
            get
            {
                return this.ikincikisitcField;
            }
            set
            {
                this.ikincikisitcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ilkKullanmaTarihi
        {
            get
            {
                return this.ilkKullanmaTarihiField;
            }
            set
            {
                this.ilkKullanmaTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isedevlet
        {
            get
            {
                return this.isedevletField;
            }
            set
            {
                this.isedevletField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool istest
        {
            get
            {
                return this.istestField;
            }
            set
            {
                this.istestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool izin
        {
            get
            {
                return this.izinField;
            }
            set
            {
                this.izinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kanal
        {
            get
            {
                return this.kanalField;
            }
            set
            {
                this.kanalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kepadres
        {
            get
            {
                return this.kepadresField;
            }
            set
            {
                this.kepadresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool kimlikdogrulandi
        {
            get
            {
                return this.kimlikdogrulandiField;
            }
            set
            {
                this.kimlikdogrulandiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool kurulumVarMi
        {
            get
            {
                return this.kurulumVarMiField;
            }
            set
            {
                this.kurulumVarMiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kvkonaytik
        {
            get
            {
                return this.kvkonaytikField;
            }
            set
            {
                this.kvkonaytikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nvidogrulama
        {
            get
            {
                return this.nvidogrulamaField;
            }
            set
            {
                this.nvidogrulamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string onaytik
        {
            get
            {
                return this.onaytikField;
            }
            set
            {
                this.onaytikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pasaportno
        {
            get
            {
                return this.pasaportnoField;
            }
            set
            {
                this.pasaportnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass
        {
            get
            {
                return this.passField;
            }
            set
            {
                this.passField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrmService.urun[] urunler
        {
            get
            {
                return this.urunlerField;
            }
            set
            {
                this.urunlerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="urun", Namespace="http://schemas.datacontract.org/2004/07/PartnerService")]
    public partial class urun : object
    {
        
        private int adetField;
        
        private decimal fiyatField;
        
        private string urunadField;
        
        private string urunkodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int adet
        {
            get
            {
                return this.adetField;
            }
            set
            {
                this.adetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal fiyat
        {
            get
            {
                return this.fiyatField;
            }
            set
            {
                this.fiyatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urunad
        {
            get
            {
                return this.urunadField;
            }
            set
            {
                this.urunadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urunkod
        {
            get
            {
                return this.urunkodField;
            }
            set
            {
                this.urunkodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="basvururesponse", Namespace="http://schemas.datacontract.org/2004/07/PartnerService")]
    public partial class basvururesponse : object
    {
        
        private string CRMIDField;
        
        private string errormessageField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMID
        {
            get
            {
                return this.CRMIDField;
            }
            set
            {
                this.CRMIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errormessage
        {
            get
            {
                return this.errormessageField;
            }
            set
            {
                this.errormessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormIletisimRequest", Namespace="http://schemas.datacontract.org/2004/07/PartnerService")]
    public partial class FormIletisimRequest : object
    {
        
        private string EmailField;
        
        private string MessageField;
        
        private string NameField;
        
        private string PhoneField;
        
        private string SubjectField;
        
        private string TcnoField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tcno
        {
            get
            {
                return this.TcnoField;
            }
            set
            {
                this.TcnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Web2.konuliste", Namespace="http://schemas.datacontract.org/2004/07/PartnerService")]
    public partial class Web2konuliste : object
    {
        
        private string baslikField;
        
        private string konuField;
        
        private string konuengField;
        
        private string konuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baslik
        {
            get
            {
                return this.baslikField;
            }
            set
            {
                this.baslikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string konu
        {
            get
            {
                return this.konuField;
            }
            set
            {
                this.konuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string konueng
        {
            get
            {
                return this.konuengField;
            }
            set
            {
                this.konuengField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string konuid
        {
            get
            {
                return this.konuidField;
            }
            set
            {
                this.konuidField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmService.IWeb2")]
    public interface IWeb2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/TurmobTest", ReplyAction="http://tempuri.org/IWeb2/TurmobTestResponse")]
        System.Threading.Tasks.Task<string> TurmobTestAsync(string crmid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/SMSCodeForMobile", ReplyAction="http://tempuri.org/IWeb2/SMSCodeForMobileResponse")]
        System.Threading.Tasks.Task<string> SMSCodeForMobileAsync(string token, string tcno, string mobilestartswith5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/SendPINPUKMailbyTCNO", ReplyAction="http://tempuri.org/IWeb2/SendPINPUKMailbyTCNOResponse")]
        System.Threading.Tasks.Task<string> SendPINPUKMailbyTCNOAsync(string token, string tcno, string teldigit, string pass, string type, string tokenserial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/CRMSATIS", ReplyAction="http://tempuri.org/IWeb2/CRMSATISResponse")]
        System.Threading.Tasks.Task<CrmService.basvururesponse> CRMSATISAsync(CrmService.basvururequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/CRMSATIS2", ReplyAction="http://tempuri.org/IWeb2/CRMSATIS2Response")]
        System.Threading.Tasks.Task<CrmService.basvururesponse> CRMSATIS2Async(CrmService.basvururequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/FormIletisim", ReplyAction="http://tempuri.org/IWeb2/FormIletisimResponse")]
        System.Threading.Tasks.Task<string> FormIletisimAsync(CrmService.FormIletisimRequest fir, string token, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb2/FormIletisimKonuListesi", ReplyAction="http://tempuri.org/IWeb2/FormIletisimKonuListesiResponse")]
        System.Threading.Tasks.Task<CrmService.Web2konuliste[]> FormIletisimKonuListesiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IWeb2Channel : CrmService.IWeb2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Web2Client : System.ServiceModel.ClientBase<CrmService.IWeb2>, CrmService.IWeb2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Web2Client(EndpointConfiguration endpointConfiguration) : 
                base(Web2Client.GetBindingForEndpoint(endpointConfiguration), Web2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Web2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Web2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Web2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Web2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Web2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> TurmobTestAsync(string crmid)
        {
            return base.Channel.TurmobTestAsync(crmid);
        }
        
        public System.Threading.Tasks.Task<string> SMSCodeForMobileAsync(string token, string tcno, string mobilestartswith5)
        {
            return base.Channel.SMSCodeForMobileAsync(token, tcno, mobilestartswith5);
        }
        
        public System.Threading.Tasks.Task<string> SendPINPUKMailbyTCNOAsync(string token, string tcno, string teldigit, string pass, string type, string tokenserial)
        {
            return base.Channel.SendPINPUKMailbyTCNOAsync(token, tcno, teldigit, pass, type, tokenserial);
        }
        
        public System.Threading.Tasks.Task<CrmService.basvururesponse> CRMSATISAsync(CrmService.basvururequest req)
        {
            return base.Channel.CRMSATISAsync(req);
        }
        
        public System.Threading.Tasks.Task<CrmService.basvururesponse> CRMSATIS2Async(CrmService.basvururequest req)
        {
            return base.Channel.CRMSATIS2Async(req);
        }
        
        public System.Threading.Tasks.Task<string> FormIletisimAsync(CrmService.FormIletisimRequest fir, string token, string pass)
        {
            return base.Channel.FormIletisimAsync(fir, token, pass);
        }
        
        public System.Threading.Tasks.Task<CrmService.Web2konuliste[]> FormIletisimKonuListesiAsync()
        {
            return base.Channel.FormIletisimKonuListesiAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWeb2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWeb2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWeb2))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.127.25:5558/Web2.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IWeb2))
            {
                return new System.ServiceModel.EndpointAddress("https://newcrm.eguven.local:5557/Web2.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWeb2,
            
            BasicHttpsBinding_IWeb2,
        }
    }
}
